### ISSUE TITLE
How the fuck do you use this?

### ISSUE THREAD

**Issue by brandonros** [everyonesdesign/OpenSearchInNewTab#3]

**Comment by everyonesdesign** [comment]
If you have search results window open and execute search in folder in Sublime Text the plugin open the search in a new tab instead of the old one.

That's theory. But in practice it fails to do that sometimes.

Here's a gif of successful opening in a new tab:

![apr-30-2017 19-47-25](https://cloud.githubusercontent.com/assets/3520704/25566242/de6402a8-2ddd-11e7-997a-0ab24bff5f5d.gif)

**Comment by dodongphure** [comment]
Just restart and it works. Thanks for this plugin

**Comment by lakesare** [comment]
You don't even need to restart it, just open some other `subl .` and close it, your current sublime should be working after that without closing it.
